export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'

export const POSTS_STATE_CHANGE = 'POSTS_STATE_CHANGE'

export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'